handlings = [
    {
      "day":"02/02/2023",
      "hour":6,
      "handlingFunction":"JARDINERA",
      "fullTimeEmployees":1,
      "partTimeEmployees":0,
      "fullTimeCost":203.50,
      "partTimeCost":2,
   },
   {
      "day":"02/02/2023",
      "hour":7,
      "handlingFunction":"JARDINERA",
      "fullTimeEmployees":1,
      "partTimeEmployees":0,
      "fullTimeCost":203.50,
      "partTimeCost":2,
   }
]